google-ID: 'UA-112060364-1'

social:
- {icon: 'twitter', link: 'https://www.twitter.com/example'}
- {icon: 'instagram', link: 'https://www.instagram.com/example'}
- {icon: 'contact', link: 'mailto:example@example.com'}

pagination:
  next_page: 'Newer'
  previous_page: 'Older'

post_date_prefix: 'Posted on'
